yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler500 = 'core.views.server_error'
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name="Текст поста",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Группа",
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Комментарий',
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='uniq_follow'
            ),
        )

yatube/posts/forms.py
from django import forms
from . models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        widgets = {
            'text': forms.Textarea(attrs={
                "cols": 40,
                "rows": 10,
                "class": "form-control",
                "required id": "id_text",
            }),
            'group': forms.Select(attrs={
                "class": "form-control",
                "id": "id_group",
            }
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        help_texts = {'text': 'Hапишите комментарий'}
        labels = {'text': 'Комментарий'}
        widgets = {
            'text': forms.Textarea(
                attrs={'class': 'form-control'}
            )
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    full_name = author.get_full_name()
    post_list = Post.objects.filter(author=author)
    post_count = post_list.count()
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    else:
        following = False
    context = {
        'full_name': full_name,
        'author': author,
        'post_count': post_count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    author = get_object_or_404(User, posts=post)
    group = post.group
    full_name = author.get_full_name()
    post_count = Post.objects.filter(author=author).count()
    comments = post.comments.all()
    context = {
        'post': post,
        'group': group,
        'full_name': full_name,
        'author': author,
        'post_count': post_count,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    else:
        form = PostForm()
    context = {
        "form": form,
        "is_create": True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post.author != request.user:
        return redirect('posts:index')
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post_detail', post_id)
    context = {
        "form": form,
        "is_edit": True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if request.resolver_match.view_name == 'posts:post_create' %}
Новый пост
{% elif request.resolver_match.view_name == 'posts:post_edit' %}
Редактировать пост
{% endif %}   
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if request.resolver_match.view_name == 'posts:post_create' %}
                Новый пост
                {% elif request.resolver_match.view_name == 'posts:post_edit' %}
                Редактировать пост
                {% endif %}           
              </div>
              <div class="card-body">        
                <form  method="post" enctype="multipart/form-data">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ form.text.label }}                   
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {% csrf_token %}
                    {{ form.text }}           
                    <small id="id_text-help" class="form-text text-muted">
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ form.group.label }}                  
                    </label>
                    {% csrf_token %}
                    {{ form.group }} 
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    {% comment %} <label for="id_image">
                      {{ form.image.label }}                  
                    </label> {% endcomment %}
                    {% csrf_token %}
                    {{ form.image }} 
                    <small id="id_group-help" class="form-text text-muted">
                      Изображение
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button action type="submit" class="btn btn-primary">
                      {% if request.resolver_match.view_name == 'posts:post_create' %}
                      Добавить
                      {% elif request.resolver_match.view_name == 'posts:post_edit' %}
                      Сохранить
                      {% endif %}
                    </button>
                  </div>
               </form>    
              </div>
            </div>
          </div>
        </div>
      </div>{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>Мои подписки</h1>
  {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">
    все записи группы
  </a>{% endif %}{% if not forloop.last %}
  <hr />{% endif %}{% endfor %}{% endcache %}{% include 'posts/includes/paginator.html' %}      
</div>{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Все записи группы {{ group.slug }}{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>{{ group }}</h1>
        <p>{{ group.description }}</p>{% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        {% if not forloop.last %}
          <hr />{% endif %}{% endfor %}{% include 'posts/includes/paginator.html' %}      
      </div>{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">
    все записи группы
  </a>{% endif %}{% if not forloop.last %}
  <hr />{% endif %}{% endfor %}{% endcache %}{% include 'posts/includes/paginator.html' %}      
</div>{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}{{ post | truncatechars:30}}{% endblock %}
{% block content %}   
    <div class="container py-5">  
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->  
            {% if post.group %} 
            <li class="list-group-item">
              Группа: {{ group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ full_name }} {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post | wordwrap:80 }}
          </p>
          {% if post.author.id == user.id %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            редактировать запись
          </a> 
          {% endif %}
          {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 
        </article>

      </div>
    </div>{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ full_name }} профайл пользователя{% endblock %}
{% block content %}
      <div class="container py-5">      
        <div class="mb-5">  
        <h1>Все посты пользователя {{ full_name }}</h1>
        <h3>Всего постов: {{ post_count }}</h3> 
        {% if user.username != author.username %}
        {% if following %}
        <a class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button">
          Отписаться
        </a>
      {% else %}
          <aclass="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button">
            Подписаться
          </aclass=>
       {% endif %}  
       {% endif %}
      </div>
        {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}      
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>   
        {% endif %}   
        {% if not forloop.last %}
        <hr>{% endif %}{% endfor %}{% include 'posts/includes/paginator.html' %}
      </div>{% endblock %}